service:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 6G
      TYPE: FABRIC
      MODRINTH_PROJECTS: |
        fabric-api
        continents
        terralith
        distant-horizons
        chunky
        lithium
        better-nether
    WHITELIST:
      - ./whitelist.txt
    OPS:
      - ./ops.txt
    volumes:
      - fabric:/data
volumes:
  fabric: {}
    