services:
  mc:
    image: itzg/minecraft-server:latest
    pull-policy: daily
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 6G
      TYPE: VANILLA
    WHITELIST:
      - ./whitelist.txt
    OPS:
      - ./ops.txt
    volumes:
      - ./mc_data:/data
  volumes:
    mc_data: {}